backend:
  name: github
  repo: mandaditos-envios/listapropiedades
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "propiedades"
    label: "Propiedades"
    folder: "_propiedades"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Precio", name: "precio", widget: "string" }
      - { label: "Descripción", name: "body", widget: "markdown" }
      - { label: "Requisitos", name: "requisitos", widget: "list" }
      - { label: "Foto Principal", name: "thumbnail", widget: "image" }
